export const MOVIES_REQUESTING = 'MOVIES_REQUESTING';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_ERROR = 'MOVIES_ERROR';

export const ADD_TO_MY_LIST_REQUESTING = 'ADD_TO_MY_LIST_REQUESTING';
export const ADD_TO_MY_LIST_SUCCESS = 'ADD_TO_MY_LIST_SUCCESS';
export const ADD_TO_MY_LIST_ERROR = ' ADD_TO_MY_LIST_ERROR';

export const MYLISTING_REQUESTING = 'MYLISTING_REQUESTING';
export const MYLISTING_SUCCESS = 'MYLISTING_SUCCESS';
export const MYLISTING_ERROR = 'MYLISTING_ERROR';